// export const list = [
//   { username: "aislisha96", imageSrc: "/img.svg", score: 10000, id: 1 },
//   { username: "ishakumn", imageSrc: "/img.svg", score: 90000, id: 2 },
//   { username: "KotuneN", imageSrc: "/img.svg", score: 80000, id: 3 },
//   { username: "aislisha96", imageSrc: "/img.svg", score: 7000, id: 4 },
//   { username: "ishakumn", imageSrc: "/img.svg", score: 7000, id: 5 },
//   { username: "KotuneN", imageSrc: "/img.svg", score: 7000, id: 6 },
//   { username: "aislisha96", imageSrc: "/img.svg", score: 7000, id: 7 },
//   { username: "ishakumn", imageSrc: "/img.svg", score: 7000, id: 8 },
//   { username: "KotuneN", imageSrc: "/img.svg", score: 7000, id: 9 },
//   { username: "aislisha96", imageSrc: "/img.svg", score: 7000, id: 10 },
//   { username: "ishakumn", imageSrc: "/img.svg", score: 7000, id: 11 },
//   { username: "KotuneN", imageSrc: "/img.svg", score: 7000, id: 12 },
//   { username: "aislisha96", imageSrc: "/img.svg", score: 7000, id: 13 },
//   { username: "aislisha96", imageSrc: "/img.svg", score: 7000, id: 14 },
//   { username: "KotuneN", imageSrc: "/img.svg", score: 7000, id: 15 },
//   { username: "aislisha96", imageSrc: "/img.svg", score: 7000, id: 16 },
//   { username: "ishakumn", imageSrc: "/img.svg", score: 7000, id: 17 },
//   { username: "KotuneN", imageSrc: "/img.svg", score: 7000, id: 18 },
//   { username: "aislisha96", imageSrc: "/img.svg", score: 7000, id: 19 },
//   { username: "ishakumn", imageSrc: "/img.svg", score: 7000, id: 20 },
//   { username: "aislisha96", imageSrc: "/img.svg", score: 7000, id: 21 },
// ];

// export const user = {
//   username: "aislisha96",
//   imageSrc: "/img.svg",
//   score: 7000,
//   id: 10,
// };
