export const list = [
    { username: "aislisha96", imageSrc: "/img.svg", score: 10000 },
    { username: "ishakumn", imageSrc: "/img.svg", score: 90000 },
    { username: "KotuneN", imageSrc: "/img.svg", score: 80000 },
    { username: "aislisha96", imageSrc: "/img.svg", score: 7000 },
    { username: "ishakumn", imageSrc: "/img.svg", score: 7000 },
    { username: "KotuneN", imageSrc: "/img.svg", score: 7000 },
    { username: "aislisha96", imageSrc: "/img.svg", score: 7000 },
    { username: "ishakumn", imageSrc: "/img.svg", score: 7000 },
    { username: "KotuneN", imageSrc: "/img.svg", score: 7000 },
    { username: "aislisha96", imageSrc: "/img.svg", score: 7000 },
    { username: "ishakumn", imageSrc: "/img.svg", score: 7000 },
    { username: "KotuneN", imageSrc: "/img.svg", score: 7000 },
    { username: "aislisha96", imageSrc: "/img.svg", score: 7000 },
    { username: "ishakumn", imageSrc: "/img.svg", score: 7000 },
    { username: "KotuneN", imageSrc: "/img.svg", score: 7000 },
    { username: "aislisha96", imageSrc: "/img.svg", score: 7000 },
    { username: "ishakumn", imageSrc: "/img.svg", score: 7000 },
    { username: "KotuneN", imageSrc: "/img.svg", score: 7000 },
    { username: "aislisha96", imageSrc: "/img.svg", score: 7000 },
    { username: "ishakumn", imageSrc: "/img.svg", score: 7000 },
    { username: "aislisha96", imageSrc: "/img.svg", score: 7000 },
];